/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppAiTutorRouteImport } from './routes/_app/ai-tutor'
import { Route as AppModulesIndexRouteImport } from './routes/_app/modules/index'
import { Route as AppModulesModuleIdRouteImport } from './routes/_app/modules/$moduleId'
import { Route as AppModulesModuleIdIndexRouteImport } from './routes/_app/modules/$moduleId.index'
import { Route as AppModulesModuleIdLessonLessonIdRouteImport } from './routes/_app/modules/$moduleId.lesson.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAiTutorRoute = AppAiTutorRouteImport.update({
  id: '/ai-tutor',
  path: '/ai-tutor',
  getParentRoute: () => AppRoute,
} as any)
const AppModulesIndexRoute = AppModulesIndexRouteImport.update({
  id: '/modules/',
  path: '/modules/',
  getParentRoute: () => AppRoute,
} as any)
const AppModulesModuleIdRoute = AppModulesModuleIdRouteImport.update({
  id: '/modules/$moduleId',
  path: '/modules/$moduleId',
  getParentRoute: () => AppRoute,
} as any)
const AppModulesModuleIdIndexRoute = AppModulesModuleIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppModulesModuleIdRoute,
} as any)
const AppModulesModuleIdLessonLessonIdRoute =
  AppModulesModuleIdLessonLessonIdRouteImport.update({
    id: '/lesson/$lessonId',
    path: '/lesson/$lessonId',
    getParentRoute: () => AppModulesModuleIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-tutor': typeof AppAiTutorRoute
  '/modules/$moduleId': typeof AppModulesModuleIdRouteWithChildren
  '/modules/': typeof AppModulesIndexRoute
  '/modules/$moduleId/': typeof AppModulesModuleIdIndexRoute
  '/modules/$moduleId/lesson/$lessonId': typeof AppModulesModuleIdLessonLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-tutor': typeof AppAiTutorRoute
  '/modules': typeof AppModulesIndexRoute
  '/modules/$moduleId': typeof AppModulesModuleIdIndexRoute
  '/modules/$moduleId/lesson/$lessonId': typeof AppModulesModuleIdLessonLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/ai-tutor': typeof AppAiTutorRoute
  '/_app/modules/$moduleId': typeof AppModulesModuleIdRouteWithChildren
  '/_app/modules/': typeof AppModulesIndexRoute
  '/_app/modules/$moduleId/': typeof AppModulesModuleIdIndexRoute
  '/_app/modules/$moduleId/lesson/$lessonId': typeof AppModulesModuleIdLessonLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-tutor'
    | '/modules/$moduleId'
    | '/modules/'
    | '/modules/$moduleId/'
    | '/modules/$moduleId/lesson/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-tutor'
    | '/modules'
    | '/modules/$moduleId'
    | '/modules/$moduleId/lesson/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/ai-tutor'
    | '/_app/modules/$moduleId'
    | '/_app/modules/'
    | '/_app/modules/$moduleId/'
    | '/_app/modules/$moduleId/lesson/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/ai-tutor': {
      id: '/_app/ai-tutor'
      path: '/ai-tutor'
      fullPath: '/ai-tutor'
      preLoaderRoute: typeof AppAiTutorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modules/': {
      id: '/_app/modules/'
      path: '/modules'
      fullPath: '/modules/'
      preLoaderRoute: typeof AppModulesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modules/$moduleId': {
      id: '/_app/modules/$moduleId'
      path: '/modules/$moduleId'
      fullPath: '/modules/$moduleId'
      preLoaderRoute: typeof AppModulesModuleIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modules/$moduleId/': {
      id: '/_app/modules/$moduleId/'
      path: '/'
      fullPath: '/modules/$moduleId/'
      preLoaderRoute: typeof AppModulesModuleIdIndexRouteImport
      parentRoute: typeof AppModulesModuleIdRoute
    }
    '/_app/modules/$moduleId/lesson/$lessonId': {
      id: '/_app/modules/$moduleId/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/modules/$moduleId/lesson/$lessonId'
      preLoaderRoute: typeof AppModulesModuleIdLessonLessonIdRouteImport
      parentRoute: typeof AppModulesModuleIdRoute
    }
  }
}

interface AppModulesModuleIdRouteChildren {
  AppModulesModuleIdIndexRoute: typeof AppModulesModuleIdIndexRoute
  AppModulesModuleIdLessonLessonIdRoute: typeof AppModulesModuleIdLessonLessonIdRoute
}

const AppModulesModuleIdRouteChildren: AppModulesModuleIdRouteChildren = {
  AppModulesModuleIdIndexRoute: AppModulesModuleIdIndexRoute,
  AppModulesModuleIdLessonLessonIdRoute: AppModulesModuleIdLessonLessonIdRoute,
}

const AppModulesModuleIdRouteWithChildren =
  AppModulesModuleIdRoute._addFileChildren(AppModulesModuleIdRouteChildren)

interface AppRouteChildren {
  AppAiTutorRoute: typeof AppAiTutorRoute
  AppModulesModuleIdRoute: typeof AppModulesModuleIdRouteWithChildren
  AppModulesIndexRoute: typeof AppModulesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiTutorRoute: AppAiTutorRoute,
  AppModulesModuleIdRoute: AppModulesModuleIdRouteWithChildren,
  AppModulesIndexRoute: AppModulesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
